#https://github.com/marketplace/actions/zeit-now-deployment
name: deploy website
on:
  push:
    tags:
      - 'v*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/now-deployment@v2
        with:
          zeit-token: ${{ secrets.ZEIT_TOKEN }} # Required
          github-token: ${{ secrets.GH_TOKEN }} #Optional
          # zeit-team-id: team_XXXXXXXXXXX #Optional
          now-args: '--prod' #Optional
          now-org-id: '${{ secrets.NOW_ORG_ID }}' #Required
          now-project-id: '${{ secrets.NOW_PROJECT_ID }}' #Required
          working-directory: ./dist
# name: deploy-site

# on:
#   push:
#     tags:
#       - 'v*'

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@master
#       - name: Build
#         run: |
#           npm run init
#           npm run build:doc

#       - name: Deploy
#         uses: JamesIves/github-pages-deploy-action@releases/v3
#         with:
#           GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
#           BRANCH: gh-pages
#           FOLDER: dist
