# Do not use now
name: deploy-site

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: deploy
        uses: amondnet/now-deployment@v1
        with:
          args: --prod
        env:
          ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
